# Generated by Django 3.1.5 on 2021-09-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='closing_status',
            new_name='has_closed',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='election_status',
            new_name='has_started',
        ),
        migrations.AlterField(
            model_name='election',
            name='real_time_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
