# Generated by Django 3.1.5 on 2021-09-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210924_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
