# Generated by Django 3.1.5 on 2021-09-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_voter_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.election')),
            ],
        ),
    ]
