# Generated by Django 3.1.5 on 2021-09-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_current_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.election'),
            preserve_default=False,
        ),
    ]
