# Generated by Django 3.1.5 on 2021-10-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_vote_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
