# Generated by Django 3.1.5 on 2021-10-02 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_voter_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.category'),
            preserve_default=False,
        ),
    ]
